"""Scan gate data models — E-001-S-006.

Defines the shared contracts for the scan pipeline:

  Action     — ALLOW / BLOCK / ALLOW_SUPPRESSED decision enum
  RiskLevel  — CRITICAL / HIGH / MEDIUM / LOW risk classification
  ScanResult — result returned by scan_or_block() and fulfilled by E-002/E-003

These types are the ONLY interface between the proxy handler (engine.py) and the
scanner implementations. Changing these models requires coordinating with E-002 and
E-003 implementations.

Architecture reference: architecture.md §5.1, §5.2
Stories: E-001-S-006 (models defined), E-002 (regex scanner fulfils contract),
         E-003 (Presidio NLP scanner fulfils contract)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class Action(str, Enum):
    """Decision action returned by the scan gate.

    ALLOW:
        Forward the request to the upstream LLM provider unchanged.

    BLOCK:
        Return HTTP 400 with ``X-OnGarde-Block: true`` to the agent.
        Do NOT open an upstream connection.

    ALLOW_SUPPRESSED:
        A pattern matched BUT an allowlist rule suppresses the block.
        Forward the request but log an ALLOW_SUPPRESSED audit event.
        Implemented in E-009 (false positive recovery).
    """

    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    ALLOW_SUPPRESSED = "ALLOW_SUPPRESSED"


class RiskLevel(str, Enum):
    """Risk classification for a BLOCK decision.

    Levels (highest → lowest):
        CRITICAL — credential / API key detected (immediate breach risk)
        HIGH     — dangerous shell command, prompt injection
        MEDIUM   — PII detected (SSN, credit card, etc.)
        LOW      — weak pattern match, advisory only

    Required when action == Action.BLOCK.
    None when action == Action.ALLOW or ALLOW_SUPPRESSED.
    """

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


@dataclass
class ScanResult:
    """Result of a scan operation returned by scan_or_block().

    Invariants (enforced by the real implementation in E-002; documented here):
      - scan_or_block() ALWAYS returns a ScanResult — it NEVER raises
      - scan_or_block() NEVER returns None
      - On ANY scan failure (exception, timeout, None return from sub-scanner),
        the wrapper returns Action.BLOCK — fail-safe policy (architecture.md §5.1)

    Fields:
        action:           Decision — ALLOW, BLOCK, or ALLOW_SUPPRESSED.
        scan_id:          ULID identifying this scan/request (from generate_ulid()).
                          Correlates log entries, audit events, and response headers.
        rule_id:          Identifier of the rule that triggered the block.
                          Required when action == BLOCK; None otherwise.
        risk_level:       Risk classification for this result.
                          Required when action == BLOCK; None otherwise.
        redacted_excerpt: A sanitised excerpt of the matched content.
                          NEVER contains raw credentials — always redacted/masked.
                          None when action == ALLOW.
        suppression_hint: A YAML snippet for the allowlist config that would suppress
                          this block (generated by E-002; always None in the stub).
        test:             True when the matched content is a known test credential
                          (e.g., an intentional canary). Used by E-007 onboarding aha moment.
        allowlist_rule_id: For ALLOW_SUPPRESSED: the allowlist entry rule_id that matched.
                          Set by apply_allowlist() in E-009. None for BLOCK and ALLOW.
    """

    action: Action
    scan_id: str
    rule_id: Optional[str] = None
    risk_level: Optional[RiskLevel] = None
    redacted_excerpt: Optional[str] = None
    suppression_hint: Optional[str] = None
    test: bool = False
    allowlist_rule_id: Optional[str] = None  # E-009: set when action=ALLOW_SUPPRESSED
